[package]
name = "cogenitor-test"
version = "0.1.0"
edition = "2024"

[dependencies]
cogenitor = { path = "../cogenitor" }
cogenitor-core = { path = "../cogenitor-core" }
http.workspace = true
serde.workspace = true
serde_json = "1.0.140"

[build-dependencies]
cogenitor = { path = "../cogenitor" }
